server:
  port: 8888
  contextPath: /
  address: 0.0.0.0

spring:
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@10.7.111.221:1521:reportdb
        username: aps
        password: Pwd123
    application:
      name: consume-service

mybatis:
  type-aliases-package: com.lakala.gate.consume.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        com.lakala.bonuspoint: info
        com.lakala.lottery: debug
        com.lakala: debug
        io.netty: info

    path: "./logs"


