server:
  port: 8082
  contextPath : /ppayMgr
spring:
  application:
    name: ppayMgr
  thymeleaf:
      prefix: classpath:/templates/pages/
      suffix: .html
      mode: HTML
      encoding: UTF-8
      cache: false
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url : jdbc:oracle:thin:@192.168.152.137:1521:xe
#    username : lkl
#    password : lkl

#mybatis:
#  type-aliases-package: com.lakala.dao.**.model
#  config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath:mybatis/**/*.xml

logging:
  file: logs/admin-client.log
  level:
    ROOT: INFO
    org.apache.ibatis: debug
    java.sql.Connection: debug
    java.sql.Statement: debug
    java.sql.PreparedStatement: debug
    com.apache.ibatis: debug


